// Mapping of logo filenames to their respective URLs for the XRPL EVM Ecosystem project.
// Add or update entries as needed to ensure each logo links to the correct project site.

const logoLinks: Record<string, string> = {
  // Wallets
  'metamask.png': 'https://metamask.io/',
  'keplr.png': 'https://www.keplr.app/',
  'crossmark.png': 'https://crossmark.io',
  'cosmostation.png': 'https://www.cosmostation.io/',
  'palmerafinance.png': 'https://app.palmeradao.xyz/create',
  'ibc.png': 'https://ibcprotocol.dev/',
  'strobe.png': 'https://strobe.finance/',
  'elys.png': 'https://app.elys.network/earn/vaults',
  'axelar.png': 'https://www.axelar.network/',
  'axelarscan.png': 'https://axelarscan.io/gmp/search',
  'squid.png': 'https://app.squidrouter.com/xrpl-xrpl-evm',
  'gaszip.png': 'https://www.gas.zip/',
  'skip.png': 'https://go.skip.build/?src_asset=uatom&src_chain=cosmoshub-4&dest_asset=axrp&dest_chain=xrplevm_1440000-1&amount_in=&amount_out=',
  'dcent.png': 'https://www.dcentwallet.com/',
  'reown.png': 'https://reown.com/',
  // Faucets & Explorers
  'faucet.png': 'https://faucet.xrplevm.org',
  'exploreme.png': 'https://xrpl.exploreme.pro/',
  'valopers.png': 'https://testnet.xrplevm.valopers.com/',
  'cosmos.png': 'https://cosmos.network/',
  'xrplnames.png': 'https://xrplnames.xyz/',
  'goldsky.png': 'https://goldsky.com/',
  'curvegrid.png': 'https://www.curvegrid.com/multibaas',
  'capsign.png': 'https://capsign.com',
  'easya.png': 'https://easya.io/',
  'moai.png': 'https://xrplevm.moai-finance.xyz/swap',
  'vertex.png': 'https://app.vertexprotocol.com/markets',
  'palmeradao.png': 'https://app.palmeradao.xyz/create',
  'riddle.png': 'https://rddl.fun/',
  'walkit.png': 'https://www.walkitapp.com/',
  'hammyfinance.png': 'https://hammy.finance/',
  'skuuy.png': 'https://skuuy.com/deploy',
  'awpswap.png': 'https://app.awpswap.io/',
  'zns.png': 'https://www.znsconnect.io/',
  'znsbio.png': 'https://zns.bio/',
  // Validators/Providers
  'blockitize.png': 'https://services.blockitize.com/?project=xrpl-evm',
  'endorphinestake.png': 'https://endorphinestake.com/',
  'unitynodes.png': 'https://unitynodes.gitbook.io/unity-nodes/testnet-network/xrpl-evm',
  'cumulo.png': 'https://cumulo.pro/services/xrplevm_mainnet/',
  'mekonglabs.png': 'https://testnet.mekonglabs.tech/xrpl/staking',
  'mictonode.png': 'https://explorer.mictonode.com/XRPL-Testnet/staking/',
  'nodeshubprovider.png': 'https://services.nodeshub.online/testnet/xrpl',
  'polkachu.png': 'https://polkachu.com/testnets/xrp',
  'enigma.png': 'https://xrp-rpc.enigma-validator.com/',
  'corenode.png': 'https://explorer.corenodehq.xyz/xrplevm-devnet/staking',
  'nodestake.png': 'https://explorer.nodestake.org/xrp',
  'stavr.png': 'https://explorer.stavr.tech/Xrpl-Testnet/staking',
  'cosmonaut.png': 'https://xrpl-testnet-rpc.cosmonautstakes.com',
  'kgnodes.png': 'https://explorer.kgnodes.xyz/Xrpl-Testnet',
  'bonynode.png': 'https://explorer.bonynode.online/xrpl',
  'hibunode.png': 'https://explorer.hibunode.com/xrplevm',
  'monkeylabs.png': 'https://explorer.monkeylabs.me/Xrpl-Testnet/staking',
  'hazennetwork.png': 'https://explorer.hazennetworksolutions.com/xrplevm-testnet',
  'hazennetworkexplorer.png': 'https://explorer.hazennetworksolutions.com/xrplevm-testnet',
  'hightower.png': 'https://htw.tech/',
  'informalsystems.png': 'https://informal.systems/',
  'range.png': 'https://app.range.org/xrpl/general',
  'ibs.png': 'https://ibs.team/',
  'bitszn.png': 'https://bitszn.com/',
  'dsrv.png': 'https://dsrv.com/',
  'posthuman.png': 'https://posthuman.digital/',
  'anam145.png': 'https://www.anamandroid.com/',
  'blockhunters.png': 'https://blockhunters.org/',
  'cosmosspaces.png': 'https://www.cosmosspaces.zone/',
  'stakecito.png': 'https://www.stakecito.com/',
  'nodevism.png': 'https://www.nodevism.com/mainnet/xrpl-evm',
  'silknodes.png': 'http://silknodes.io/testnets/xrplevm',
  'validator247.png': 'https://validator247.com/',

  // Oracles
  'band.png': 'https://www.bandprotocol.com/',
  'api3.png': 'https://api3.org/',
  // Misc
  'xrplcommons.png': 'https://xrplcommons.org',
  'xrise33.png': 'https://xrise33.com',
  'grove.png': 'https://grove.city/public-endpoints',
  'imperator.png': 'https://www.imperator.co/services/chain-services/mainnets/xrp',
  'itrocket.png': 'https://itrocket.net/services/testnet/xrplevm/',
  'dongqn.png': 'https://services.dongqn.com/xrpl-evm-testnet',
  'rpcdot.png': 'https://explorer.rpcdot.com/xrplevm-testnet',
  'luckystar.png': 'https://explorer.luckystar.asia/XRPL-Mainnet',
  'xrplmetamasksnap.png': 'https://wallet.xrplevm.org',
  'zstake.png': 'https://explorer.zstake.xyz/exrp',
  // --- Missing links, fill as needed ---
  // Auditors
  'bishopfox.png': 'https://ripple.com/reports/Ripple-Side-Chains-Assessment-Report-XRPL.pdf',
  'certik.png': 'https://drive.google.com/file/d/1X8wCfIXolZMqQ4KfRl03vpgPx2v6GB8c/view',
  'fyeo.png': 'https://drive.google.com/file/d/16R3XBCQ-FhFEQQevwRNlnUUE0e_GsuSe/view',
  'nccgroup1.png': 'https://drive.google.com/file/d/1CT-TObFviDNYyvXQ2RqXWqom_d7G07-6/view',
  'nccgroup2.png': 'https://drive.google.com/file/d/1rtCe9etAZAOn61AIo2m6-ExcKUHK5THP/view',
  'nccgroup3.png': 'https://drive.google.com/file/d/14fhn4yYoTpYsdfXLjOfdMPiu2TmsWb2a/view',
  // Core
  'commonprefix.png': 'https://www.commonprefix.com/',
  'peersyst.png': 'https://peersyst.com/',
  'ripple.png': 'https://ripple.com/',
  // dApps
  'axiom.png': 'https://www.axiomprotocol.io/',
  'fomobiz.png': 'https://fomo.biz/',
  'gas.zip.png': 'https://www.gas.zip/',
  'injective.png': 'https://injective.com/',
  'redgervoir.png': 'https://redgervoir.com/',
  'helix.png': 'https://helixapp.com/futures/xrp-usdt-perp',
  'mars.png': 'https://marsgate.xyz/',
  'nexusdao.png': 'https://nexus.dao.ai/',
  'nexusdapp.png': 'https://www.thenexusportal.io/',
  'nfts2me.png': 'https://nfts2me.com/',
  'onchaingm.png': 'https://onchaingm.com/',
  'purplemarkets.png': 'https://www.purple-trading.com/',
  'securd.png': 'https://www.securd.org/',
  'xaodao.png': 'https://www.xaodao.io',
  'surgedex.png': 'https://surge.syvlabs.io/',
  'mintiq-market.png': 'https://mintiq.market/',
  'anodex.png': 'https://dex.anodos.finance/',
  'chainsatlas.png': 'https://platform.chainsatlas.com/',
  'hydro.png': 'https://hydro.cosmos.network/',
  'noble.png': 'https://www.noble.xyz/',
  'osmosis.png': 'https://www.osmosis.zone/',
  'stakz.png': 'https://stakz.io/',
  'chaingun.png': 'https://chaingun.xyz/',
  'falcon.png': 'https://falcon.finance/',
  'midasrwa.png': 'https://midas.app/',
  'ripplebids.png': 'https://ripplebids.com/',
  'rubyscore.png': 'https://rubyscore.io/',
  'liquify.png': 'https://liquify.fi/',
  'zkcodex.png': 'https://zkcodex.com/xrpl',
  'conft.png': 'https://conft.app',
  'copass.png': 'https://copass.app',
  'copump.png': 'https://copump.xyz',
  'geochain.png': 'https://geo-chain.xyz/',
  'xrpawz.png': 'https://xrpawz.com',
  'yellow.png': 'https://www.yellow.org/',
  'explorer-dapp-ens.png': 'https://ens.xrplevm.org/',
  'explorer-dapp-reown-dapp.png': 'https://reown-xrpl-dapp.vercel.app/',

  // Bridges

  'cobridge.png': 'https://cobridge.xyz',
  

  // Explorers
  'blockscout.png': 'https://explorer.xrplevm.org/',
  'forbole_bigd 1.png': 'https://governance.xrplevm.org/',
  'nodeshubexplorer.png': 'https://explorer.nodeshub.online/xrpl',
  'interscan.png': 'https://xrplevm.interscan.pro/',
  'winsnip.png': 'https://winscan.winsnip.xyz/xrpl-mainnet',
  // Providers
  'xss.png': 'https://services.xsslabs.tech/xrpl-evm/installation',
  'noders.png': 'https://noders.services/mainnet/xrp',
  
  // Validators
  'bkgeomatics.png': 'https://bkxrplevm.com/',
  'cryptosurvivor.png': 'https://governance.xrplevm.org/xrplevm/validators/ethmvaloper149nrrm3qzjl9mg5av9gnle9qrmzrrsxysk6p82',
  'flowdesk.png': 'https://www.flowdesk.co/',
  'sbi.png': 'https://defimans.com/en/',
  'interchainlabs.png': 'https://interchain.io/',
  'kingnodes.png': 'https://www.kingnodes.com/',
  'kintsugi.png': 'https://kintsugi.tech/',
  'linkpool.png': 'https://linkpool.com/',
  'nexus.png': 'https://www.thenexusportal.io/',
  'rhino.png': 'https://rhinostake.com/',
  'sg1.png': 'https://sg-1.online/',
  'cryptocrew.png': 'https://ccvalidators.com/',
  // Wallets
  'leap.png': 'https://www.leapwallet.io/',
  'bifrost.png': 'https://bifrostwallet.com',
  'joey.png': 'https://joeywallet.xyz',
  'xaman.png': 'https://xaman.app',
  'girin.png': 'https://girin.app',
  // Add more as needed
};

export default logoLinks;
